// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DbDevTicketappContext))]
    [Migration("20260719145725_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Boleto", b =>
                {
                    b.Property<int>("IdBoleto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_boleto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBoleto"));

                    b.Property<DateTime?>("FechaCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_compra")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdEventoLocalidad")
                        .HasColumnType("int")
                        .HasColumnName("id_evento_localidad");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NumBoleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("num_boleto");

                    b.HasKey("IdBoleto");

                    b.HasIndex("IdEventoLocalidad");

                    b.HasIndex("IdFactura");

                    b.HasIndex("IdUsuario");

                    b.HasIndex(new[] { "NumBoleto" }, "UQ__boleto__5F58F54E312BB92F")
                        .IsUnique();

                    b.ToTable("boleto", (string)null);
                });

            modelBuilder.Entity("API.Models.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_evento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvento"));

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_evento");

                    b.Property<TimeOnly>("HoraEvento")
                        .HasColumnType("time")
                        .HasColumnName("hora_evento");

                    b.Property<string>("NombreEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_evento");

                    b.HasKey("IdEvento");

                    b.ToTable("evento", (string)null);
                });

            modelBuilder.Entity("API.Models.EventoLocalidad", b =>
                {
                    b.Property<int>("IdEventoLocalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_evento_localidad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEventoLocalidad"));

                    b.Property<int>("CapacidadDisponible")
                        .HasColumnType("int")
                        .HasColumnName("capacidad_disponible");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int")
                        .HasColumnName("id_evento");

                    b.Property<int>("IdLocalidad")
                        .HasColumnType("int")
                        .HasColumnName("id_localidad");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio");

                    b.HasKey("IdEventoLocalidad");

                    b.HasIndex("IdEvento");

                    b.HasIndex("IdLocalidad");

                    b.ToTable("evento_localidad", (string)null);
                });

            modelBuilder.Entity("API.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<DateTime?>("FechaFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_factura")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdMedioPago")
                        .HasColumnType("int")
                        .HasColumnName("id_medio_pago");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_factura");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdMedioPago");

                    b.HasIndex("IdUsuario");

                    b.HasIndex(new[] { "NumeroFactura" }, "UQ__factura__3DC4B241A96C28B6")
                        .IsUnique();

                    b.ToTable("factura", (string)null);
                });

            modelBuilder.Entity("API.Models.Localidad", b =>
                {
                    b.Property<int>("IdLocalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_localidad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocalidad"));

                    b.Property<int>("IdSedeEvento")
                        .HasColumnType("int")
                        .HasColumnName("id_sede_evento");

                    b.Property<string>("NombreLocalidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_localidad");

                    b.HasKey("IdLocalidad");

                    b.HasIndex("IdSedeEvento");

                    b.ToTable("localidad", (string)null);
                });

            modelBuilder.Entity("API.Models.MedioPago", b =>
                {
                    b.Property<int>("IdMedioPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_medio_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedioPago"));

                    b.Property<string>("NombreMedioPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_medio_pago");

                    b.HasKey("IdMedioPago");

                    b.ToTable("medio_pago", (string)null);
                });

            modelBuilder.Entity("API.Models.SedeEvento", b =>
                {
                    b.Property<int>("IdSedeEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sede_evento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSedeEvento"));

                    b.Property<string>("NombreSedeEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_sede_evento");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ubicacion");

                    b.HasKey("IdSedeEvento");

                    b.ToTable("sede_evento", (string)null);
                });

            modelBuilder.Entity("API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correo");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex(new[] { "Correo" }, "UQ__usuario__2A586E0B492B5F82")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("API.Models.Boleto", b =>
                {
                    b.HasOne("API.Models.EventoLocalidad", "IdEventoLocalidadNavigation")
                        .WithMany("Boletos")
                        .HasForeignKey("IdEventoLocalidad")
                        .IsRequired()
                        .HasConstraintName("FK_evento_localidad");

                    b.HasOne("API.Models.Factura", "IdFacturaNavigation")
                        .WithMany("Boletos")
                        .HasForeignKey("IdFactura")
                        .IsRequired()
                        .HasConstraintName("FK_factura");

                    b.HasOne("API.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Boletos")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_usuario");

                    b.Navigation("IdEventoLocalidadNavigation");

                    b.Navigation("IdFacturaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("API.Models.EventoLocalidad", b =>
                {
                    b.HasOne("API.Models.Evento", "IdEventoNavigation")
                        .WithMany("EventoLocalidads")
                        .HasForeignKey("IdEvento")
                        .IsRequired()
                        .HasConstraintName("FK_evento");

                    b.HasOne("API.Models.Localidad", "IdLocalidadNavigation")
                        .WithMany("EventoLocalidads")
                        .HasForeignKey("IdLocalidad")
                        .IsRequired()
                        .HasConstraintName("FK_localidad");

                    b.Navigation("IdEventoNavigation");

                    b.Navigation("IdLocalidadNavigation");
                });

            modelBuilder.Entity("API.Models.Factura", b =>
                {
                    b.HasOne("API.Models.MedioPago", "IdMedioPagoNavigation")
                        .WithMany("Facturas")
                        .HasForeignKey("IdMedioPago")
                        .IsRequired()
                        .HasConstraintName("FK_factura_medio_pago");

                    b.HasOne("API.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Facturas")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_factura_usuario");

                    b.Navigation("IdMedioPagoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("API.Models.Localidad", b =>
                {
                    b.HasOne("API.Models.SedeEvento", "IdSedeEventoNavigation")
                        .WithMany("Localidads")
                        .HasForeignKey("IdSedeEvento")
                        .IsRequired()
                        .HasConstraintName("FK_localidad_sede_evento");

                    b.Navigation("IdSedeEventoNavigation");
                });

            modelBuilder.Entity("API.Models.Evento", b =>
                {
                    b.Navigation("EventoLocalidads");
                });

            modelBuilder.Entity("API.Models.EventoLocalidad", b =>
                {
                    b.Navigation("Boletos");
                });

            modelBuilder.Entity("API.Models.Factura", b =>
                {
                    b.Navigation("Boletos");
                });

            modelBuilder.Entity("API.Models.Localidad", b =>
                {
                    b.Navigation("EventoLocalidads");
                });

            modelBuilder.Entity("API.Models.MedioPago", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("API.Models.SedeEvento", b =>
                {
                    b.Navigation("Localidads");
                });

            modelBuilder.Entity("API.Models.Usuario", b =>
                {
                    b.Navigation("Boletos");

                    b.Navigation("Facturas");
                });
#pragma warning restore 612, 618
        }
    }
}
